### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by markspolakovs** [ColinRoitt/IsItCandidateInterviewNight#9]

**Comment by michael-grace** [comment]
yes plz fix

**Comment by ColinRoitt** [comment]
Issue resolving FTP domain with hosting provider - a ticket has been submitted with 3rd party.

**Comment by michael-grace** [comment]
Thank you for your quick response as a response to the filed issue. I know I for one am looking forward to the continued progress on the resolution of this issue.

**Comment by ColinRoitt** [comment]
Issue now resolved https://github.com/ColinRoitt/IsItCandidateInterviewNight/commit/38b1d469bf30514677cc61aff9775ef2b3bb354c

No domain record was set for FTP subdomain used for deployment.
